### ISSUE TITLE
Implement RelyingParty.serialize() method

### ISSUE THREAD

**Issue by dmitrizagidulin** [anvilresearch/oidc-rp#2]
Any chance we can have a `serialize()` instance method on relying party? (similar to the one in connect-nodejs client).

**Comment by christiansmith** [comment]
We will actually need a `deserialize()` method at the very least, and it needs to be asynchronous because of importing the JWK Set back into `webcrypto`. So yes, totally. Any other requirements you can think of besides just `JSON.stringify()`ing?

**Comment by dmitrizagidulin** [comment]
No other requirements, as long as (like you mention) we have a round-trip way to rehydrate a serialized RP (via a `deserialize()`, or better yet a `create()` method). (The async/JWKSet import part is unfortunate, but nothing to be done about it).

**Comment by dmitrizagidulin** [comment]
Arrr. Wherrrz my serialize(), mateys?

**Comment by dmitrizagidulin** [comment]
Implemented & merged. Closing.
