### ISSUE TITLE
Handle error HTTP status codes

### ISSUE THREAD

**Issue by dan-f** [anvilresearch/oidc-rp#26]
The whatwg fetch API doesn't reject when HTTP responses are "bad": https://github.com/github/fetch#caveats

This is causing some unexpected errors in registration. For example request to `${origin}/.well-known/openid-configuration` tries to parse a JSON response body, even if the response returns a 404.

https://github.com/anvilresearch/oidc-rp/blob/master/src/RelyingParty.js#L154

**Comment by christiansmith** [comment]
Thanks, looking into it.

**Comment by dmitrizagidulin** [comment]
Fixed in v0.3.0, closing.
